name: Run on Push to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.4.0
    
    - name: Use Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '20'

    - name: Install dependencies
      run: cd project5/client && npm ci

    - name: Build project
      run: cd project5/client && npm run build

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.2

    - name: Build server
      run: |
        cd project5/server
        go build main.go

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 # Replace with your desired AWS region

    - name: Query EC2 instances
      id: ec2_instances
      run: |
        # List all EC2 instances
        EC2_INSTANCES=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId, InstanceType, State.Name, PrivateIpAddress, PublicIpAddress, Tags[?Key==`Name`].Value[]]' --output table)
        echo "EC2 Instances:"
        echo "$EC2_INSTANCES"
        echo "ec2_instances=$EC2_INSTANCES" >> $GITHUB_OUTPUT

    - name: Echo EC2 instances
      run: echo "${{ steps.ec2_instances.outputs.ec2_instances }}"
