name: Run on Push to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.4.0
    
    - name: Use Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '20'

    - name: Install dependencies
      run: cd project5/client && npm ci

    - name: Build project
      run: cd project5/client && npm run build

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.2

    - name: Build server
      run: |
        cd project5/server
        go build main.go

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
          
    - name: Get EC2 public IP
      id: get-ec2-public-ip
      run: |
        EC2_PUBLIC_IP=$(aws ec2 describe-instances \
                        --instance-ids i-0558fc39891c05906 \
                        --query 'Reservations[0].Instances[0].PublicIpAddress' \
                        --output text)
        echo "::set-output name=ec2-public-ip::$EC2_PUBLIC_IP"
    
        #    - name: Copy files to EC2 instance
        #      run: |
        #        scp -r -o StrictHostKeyChecking=no project5/client/build ec2-user@YOUR_EC2_PUBLIC_IP:/path/on/ec2/instance
        #        scp -o StrictHostKeyChecking=no project5/server/main ec2-user@YOUR_EC2_PUBLIC_IP:/path/on/ec2/instance

