name: Run on Push to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.4.0
    
    - name: Use Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '20'

    - name: Install dependencies
      run: cd project5/client && npm ci

    - name: Build project
      run: cd project5/client && npm run build

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.2

    - name: Build server
      run: |
        cd project5/server
        go build main.go
