name: Run on Push to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.4.0

    - name: Use Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '20'

    - name: Install dependencies
      run: cd project5/client && npm ci

    - name: Build project
      run: cd project5/client && npm run build

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.2

    - name: Build server
      run: |
        cd project5/server
        go build main.go

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 # Replace with your desired AWS region

    - name: Get EC2 instance IP
      id: ec2_instance_ip
      run: |
        INSTANCE_ID="i-0558fc39891c05906" # Replace with your instance ID
        INSTANCE_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
        echo "Instance IP: $INSTANCE_IP"
        echo "instance_ip=$INSTANCE_IP" >> $GITHUB_OUTPUT

    - name: Echo EC2 instance IP
      run: echo "The IP address of the EC2 instance is ${{ steps.ec2_instance_ip.outputs.instance_ip }}"


    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ steps.ec2_instance_ip.outputs.instance_ip }}

    - name: Remove existing client directory
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.ec2_instance_ip.outputs.instance_ip }} "rm -rf /home/ubuntu/webapps/vimtube/client"

    - name: Create client directory
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.ec2_instance_ip.outputs.instance_ip }} "mkdir -p /home/ubuntu/webapps/vimtube/client"

    - name: Copy client files to EC2 instance
      run: |
        scp -r -o StrictHostKeyChecking=no project5/client/build ubuntu@${{ steps.ec2_instance_ip.outputs.instance_ip }}:/home/ubuntu/webapps/vimtube/client

    - name: Remove existing server directory
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.ec2_instance_ip.outputs.instance_ip }} "rm -rf /home/ubuntu/webapps/vimtube/server"

    - name: Create server directory
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.ec2_instance_ip.outputs.instance_ip }} "mkdir -p /home/ubuntu/webapps/vimtube/server"

    - name: Copy server files to EC2 instance
      run: |
        scp -o StrictHostKeyChecking=no project5/server/main ubuntu@${{ steps.ec2_instance_ip.outputs.instance_ip }}:/home/ubuntu/webapps/vimtube/server

    - name: Start process with PM2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.ec2_instance_ip.outputs.instance_ip }} "cd /home/ubuntu/webapps/vimtube/server && export BUCKET_NAME='${{ secrets.S3_BUCKET_NAME }}' && export SERVER_ENV=production && pm2 delete my-process || true; pm2 start ./main --name my-process"
